# Generated by Django 4.1.1 on 2022-10-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('vorname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('thema', models.CharField(max_length=100)),
                ('session_chair', models.CharField(max_length=60)),
                ('note', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
